title: CAIO Playbook
subtitle: AI Transformation Guide for 100-500 Person Organizations
description: >-
  A comprehensive guide for Chief AI Officers leading AI transformation in mid-sized organizations.
  Practical frameworks, implementation strategies, and real-world insights.
author: Your Name
email: your-email@example.com
baseurl: "/caio-play-book"
url: "https://yourusername.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalink structure
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CAIO Playbook Team"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
header_pages:
  - about.md
  - archive.md